### ISSUE TITLE
yorum

### ISSUE THREAD

**Issue by ismly** [ahm3tcelik/SocialText#1]
Çok güzel olmuş, emeğinize sağlık. Yorum yapma özelliği eklemek zor olur mu acaba ya?

**Comment by ahm3tcelik** [comment]
Öncelikle teşekkürler. Yorum yapma özelliğinin eklenmesi de çok zor olmaz. Cloud Firestore tarafında 'Yorumlar' diye bir koleksiyon oluşturursunuz. Bu koleksiyonda yorumu atan kullanıcı id, post id, yorum içeriği, tarih gibi bilgilerin tutulması yeterli olur.
